<?php

namespace ContainerV2xbFpl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zd3zYo2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zd3zYo2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zd3zYo2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenement' => ['privates', '.errored..service_locator.Zd3zYo2.App\\Entity\\Evenements', NULL, 'Cannot autowire service ".service_locator.Zd3zYo2": it needs an instance of "App\\Entity\\Evenements" but this type has been excluded in "config/services.yaml".'],
        ], [
            'evenement' => 'App\\Entity\\Evenements',
        ]);
    }
}
