<?php

namespace ContainerV2xbFpl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HNJdGbKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hNJdGbK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hNJdGbK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AcceuilController::index' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\AchatController::ajouter' => ['privates', '.service_locator.Zd3zYo2', 'get_ServiceLocator_Zd3zYo2Service', true],
            'App\\Controller\\AchatController::index' => ['privates', '.service_locator.icM9jVd', 'get_ServiceLocator_IcM9jVdService', true],
            'App\\Controller\\CategorieController::ajouter' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\CategorieController::list' => ['privates', '.service_locator.zUQ8hHY', 'get_ServiceLocator_ZUQ8hHYService', true],
            'App\\Controller\\EvenementController::ajout' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.Zd3zYo2', 'get_ServiceLocator_Zd3zYo2Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QaaDzHL', 'get_ServiceLocator_QaaDzHLService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AcceuilController:index' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\AchatController:ajouter' => ['privates', '.service_locator.Zd3zYo2', 'get_ServiceLocator_Zd3zYo2Service', true],
            'App\\Controller\\AchatController:index' => ['privates', '.service_locator.icM9jVd', 'get_ServiceLocator_IcM9jVdService', true],
            'App\\Controller\\CategorieController:ajouter' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\CategorieController:list' => ['privates', '.service_locator.zUQ8hHY', 'get_ServiceLocator_ZUQ8hHYService', true],
            'App\\Controller\\EvenementController:ajout' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.Zd3zYo2', 'get_ServiceLocator_Zd3zYo2Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QaaDzHL', 'get_ServiceLocator_QaaDzHLService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AcceuilController::index' => '?',
            'App\\Controller\\AchatController::ajouter' => '?',
            'App\\Controller\\AchatController::index' => '?',
            'App\\Controller\\CategorieController::ajouter' => '?',
            'App\\Controller\\CategorieController::list' => '?',
            'App\\Controller\\EvenementController::ajout' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AcceuilController:index' => '?',
            'App\\Controller\\AchatController:ajouter' => '?',
            'App\\Controller\\AchatController:index' => '?',
            'App\\Controller\\CategorieController:ajouter' => '?',
            'App\\Controller\\CategorieController:list' => '?',
            'App\\Controller\\EvenementController:ajout' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
