<?php

namespace ContainerRxX6Lp9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IcM9jVdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.icM9jVd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.icM9jVd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenementsRepository' => ['privates', 'App\\Repository\\EvenementsRepository', 'getEvenementsRepositoryService', true],
        ], [
            'evenementsRepository' => 'App\\Repository\\EvenementsRepository',
        ]);
    }
}
