<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTPGZLA7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTPGZLA7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTPGZLA7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTPGZLA7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTPGZLA7\App_KernelDevDebugContainer([
    'container.build_hash' => 'TPGZLA7',
    'container.build_id' => '95da3d47',
    'container.build_time' => 1705912471,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTPGZLA7');
